<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ASCII_img_converter</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260531" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260531" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
  </ItemGroup>

</Project>
